# Generated by Django 4.2.4 on 2023-08-19 17:41

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Link",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                ("url", models.URLField(unique=True)),
                ("slug", models.SlugField(blank=True, max_length=100, unique=True)),
                ("clicks", models.PositiveIntegerField(default=0)),
            ],
        ),
    ]
